[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22"

[[headers]]
  for = "/embed"
  [headers.values]
    Content-Security-Policy = "frame-ancestors *;"

[[headers]]
  for = "/embed/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors *;"
